// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuvsB0pTSjFuafliVnq6rvofznnXOU_Zk',
    appId: '1:656783991102:web:f5d5d899e24cc4f3850c6f',
    messagingSenderId: '656783991102',
    projectId: 'bloclearn-fffcb',
    authDomain: 'bloclearn-fffcb.firebaseapp.com',
    storageBucket: 'bloclearn-fffcb.firebasestorage.app',
    measurementId: 'G-0QGTT1VNKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrssgs7ptVtl45E5jiOlSE15SyoGfeWbo',
    appId: '1:656783991102:android:7bf209ab6fd8b37d850c6f',
    messagingSenderId: '656783991102',
    projectId: 'bloclearn-fffcb',
    storageBucket: 'bloclearn-fffcb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDr3kaFUZ5r8fYy_N7Havf7vdASa4BNxXo',
    appId: '1:656783991102:ios:1f78c8f7271b4365850c6f',
    messagingSenderId: '656783991102',
    projectId: 'bloclearn-fffcb',
    storageBucket: 'bloclearn-fffcb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDr3kaFUZ5r8fYy_N7Havf7vdASa4BNxXo',
    appId: '1:656783991102:ios:1f78c8f7271b4365850c6f',
    messagingSenderId: '656783991102',
    projectId: 'bloclearn-fffcb',
    storageBucket: 'bloclearn-fffcb.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuvsB0pTSjFuafliVnq6rvofznnXOU_Zk',
    appId: '1:656783991102:web:6cf056cc005a2529850c6f',
    messagingSenderId: '656783991102',
    projectId: 'bloclearn-fffcb',
    authDomain: 'bloclearn-fffcb.firebaseapp.com',
    storageBucket: 'bloclearn-fffcb.firebasestorage.app',
    measurementId: 'G-K2S8F6K05N',
  );
}
